title = "Home"
baseURL = "https://chatter19.github.io/partha_pratim_chatterjee_portfolio/"
languageCode = "en-us"
theme = "ananke"
#themesDir = "../.."

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true
canonifyURLs = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "The last theme you'll ever need. Maybe."
  facebook = ""
  #twitter = "https://twitter.com/KenJee_DS"
  instagram = ""
  #youtube = "https://www.youtube.com/channel/UCiT9RITQ9PW6BhXK0y2jaeg"
  #github = "https://github.com/PlayingNumbers"
  gitlab = ""
  #linkedin = "https://www.linkedin.com/in/kenjee/"
  mastodon = ""
  slack = ""
  stackoverflow = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 2
